In [ ]:
%tensorflow_version 2.x

TensorFlow 2.x selected.


In [1]:
import numpy as np
import tensorflow as tf

In [2]:
class BGDRegression(object):
  def __init__(self, eta=0.1, n_iter=1000):
    self.eta=eta
    self.n_iter=n_iter
  def fit(self, X, y):
    m,n=X.shape
    ones=tf.ones(shape=[m,1], dtype=tf.dtypes.float64)
    X= tf.concat([ones, X], axis=1)

    self.theta = tf.Variable(tf.random.normal(shape=[n+1, 1], dtype=tf.dtypes.float64))
    for i in range(self.n_iter):
      gradients = 2 / m * tf.transpose(X) @ (X @ self.theta - y)
      self.theta.assign(self.theta - self.eta * gradients)
    return self
  def predict(self,X):
    m,n=X.shape
    ones=tf.ones(shape=[m,1], dtype=tf.dtypes.float64)
    X = tf.concat([ones, X], axis=1)
    return X @ self.theta 


In [3]:
from tensorflow.keras.datasets import boston_housing

In [4]:
(X_train, y_train), (X_test, y_test) = boston_housing.load_data()

57026/57026 [==============================] - 0s 0us/step


In [5]:
X_train.shape

(404, 13)

In [6]:
y_train.shape

(404,)

In [7]:
X_test.shape

(102, 13)

In [8]:
y_train = y_train.reshape(-1, 1)

In [9]:
y_test = y_test.reshape(-1, 1)

In [10]:
mean = tf.reduce_mean(X_train, axis= 1, keepdims=True)

In [11]:
std = tf.math.reduce_std(X_train, axis=1 , keepdims=True)

In [12]:
X_scaled = (X_train - mean) / std

In [13]:
bgd_reg = BGDRegression()

In [14]:
X_train = tf.Variable(X_scaled) 

In [15]:
y_train = tf.Variable(y_train)

In [16]:
bgd_reg.fit(X_train, y_train)

In [17]:
bgd_reg.theta

<tf.Variable 'Variable:0' shape=(14, 1) dtype=float64, numpy=
array([[-2.63404415e+198],
       [ 1.26688475e+198],
       [ 1.06798162e+198],
       [ 1.11959415e+198],
       [ 1.31689218e+198],
       [ 1.30757831e+198],
       [ 1.19512969e+198],
       [ 2.44460006e+196],
       [ 1.24090724e+198],
       [ 1.16613995e+198],
       [-5.95123389e+198],
       [ 9.61562027e+197],
       [-5.79987415e+198],
       [ 1.08399212e+198]])>

In [18]:
bgd_reg.predict(X_train)

<tf.Tensor: shape=(404, 1), dtype=float64, numpy=
array([[-3.50033688e+199],
       [-3.47943268e+199],
       [-3.40817520e+199],
       [-3.38305604e+199],
       [-3.42608308e+199],
       [-3.49028900e+199],
       [-3.43102408e+199],
       [-3.53887112e+199],
       [-3.24210098e+199],
       [-3.53600280e+199],
       [-3.40803737e+199],
       [-2.56009894e+199],
       [-3.49116455e+199],
       [-3.37709572e+199],
       [-3.31739715e+199],
       [-2.48811488e+199],
       [-3.42652873e+199],
       [-3.50315013e+199],
       [-3.49337387e+199],
       [-3.54362275e+199],
       [-2.52429303e+199],
       [-3.38951025e+199],
       [-3.48045556e+199],
       [-3.49683779e+199],
       [-3.38861237e+199],
       [-3.43114925e+199],
       [-3.51228966e+199],
       [-3.42638108e+199],
       [-3.51270640e+199],
       [-3.54499112e+199],
       [-3.47776935e+199],
       [-3.41900967e+199],
       [-3.25014813e+199],
       [-3.50627477e+199],
       [-3.38512934e+199],
     